#include "create_data_base.h"
#include<iostream>

void CreateDataBase() {
  std::string sql = "CREATE TABLE IF NOT EXISTS SBERBANK(ID, NAME, LEGALSUBJECT, BIRTHDAY, ADDRESS, PASSPORT, DEPOSIT, DEBIT, CREDIT );";
  SqlCin(sql);
  sql =  "CREATE TABLE IF NOT EXISTS ALPHABANK(ID, NAME, LEGALSUBJECT, BIRTHDAY, ADDRESS, PASSPORT, DEPOSIT, DEBIT, CREDIT );";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS TINKOFF(ID, NAME, LEGALSUBJECT, BIRTHDAY, ADDRESS, PASSPORT, DEPOSIT, DEBIT, CREDIT );";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS ALPHABANK_CREDIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS SBERBANK_CREDIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS TINKOFF_CREDIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);

  sql = "CREATE TABLE IF NOT EXISTS SBERBANK_DEBIT(ID, MONEY );";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS ALPHABANK_DEBIT(ID, MONEY );";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS TINKOFF_DEBIT(ID, MONEY);";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS SBERBANK_DEPOSIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS ALPHABANK_DEPOSIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS TINKOFF_DEPOSIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS CENTRAL_BANK(BANK, MONEY);";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS CENTRAL_BANK_OPERATIONS(ID_SENDER, ID_RECIPIENT, BANK_SENDER, BANK_RECIPIENT, MONEY);";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS SBERBANK_OPERATIONS(ID_SENDER, ID_RECIPIENT, MONEY);";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS ALPHABANK_OPERATIONS(ID_SENDER, ID_RECIPIENT, MONEY);";
  SqlCin(sql);
  sql = "CREATE TABLE IF NOT EXISTS TINKOFF_OPERATIONS(ID_SENDER, ID_RECIPIENT, MONEY);";
  SqlCin(sql);
}
