#include "create_data_base.h"
#include<iostream>

void CreateDataBase() {
  std::string sql = "CREATE TABLE SBERBANK(ID, NAME, LEGALSUBJECT, BIRTHDAY, ADDRESS, PASSPORT, DEPOSIT, DEBIT, CREDIT );";
  std::cout<<"'fgaeg";
  SqlCin(sql);
  sql =  "CREATE TABLE ALPHABANK(ID, NAME, LEGALSUBJECT, BIRTHDAY, ADDRESS, PASSPORT, DEPOSIT, DEBIT, CREDIT );";
  SqlCin(sql);
  sql = "CREATE TABLE TINKOFF(ID, NAME, LEGALSUBJECT, BIRTHDAY, ADDRESS, PASSPORT, DEPOSIT, DEBIT, CREDIT );";
  SqlCin(sql);
  sql = "CREATE TABLE ALPHABANK_CREDIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);
  sql = "CREATE TABLE SBERBANK_CREDIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);
  sql = "CREATE TABLE TINKOFF_CREDIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);

  sql = "CREATE TABLE SBERBANK_CREDIT(ID, MONEY );";
  SqlCin(sql);
  sql = "CREATE TABLE ALPHABANK_CREDIT(ID, MONEY );";
  SqlCin(sql);
  sql = "CREATE TABLE TINKOFF_CREDIT(ID, MONEY);";
  SqlCin(sql);
  sql = "CREATE TABLE SBERBANK_CREDIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);
  sql = "CREATE TABLE ALPHABANK_CREDIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);
  sql = "CREATE TABLE TINKOFF_CREDIT(ID, MONEY, PERCENTS );";
  SqlCin(sql);
  sql = "CREATE TABLE CENTRAL_BANK(BANK, MONEY);";
  SqlCin(sql);
  sql = "CREATE TABLE CENTRAL_BANK_OPERATIONS(ID_SENDER, ID_RECIPIENT, BANK_SENDER, BANK_RECIPIENT, MONEY);";
  SqlCin(sql);
  sql = "CREATE TABLE SBERBANK_OPERATIONS(ID_SENDER, ID_RECIPIENT, MONEY);";
  SqlCin(sql);
  sql = "CREATE TABLE ALPHABANK_OPERATIONS(ID_SENDER, ID_RECIPIENT, MONEY);";
  SqlCin(sql);
  sql = "CREATE TABLE TINKOFF_OPERATIONS(ID_SENDER, ID_RECIPIENT, MONEY);";
  SqlCin(sql);
}
